//! Harder decode vectors: exactly K (or K+1) received symbols, mostly/only repair symbols, plus a search
//! for patterns on which the reference decoder FAILS (singular matrix, ok=0).
//! Usage: cargo run --release -- <out_dir>      (default ../../tests/vectors2)
//! Files (same line formats as tests/vectors, see tests/vectors/README.md): encoded.txt, decode.txt.
//! Decode kind codes: 3 = exactly K, all repair; 4 = exactly K, 1/4 source; 5 = exactly K, 1/2 source;
//! 6 = failure probe (exactly K, all repair, reference decoder fails); 7 = K+1, all repair.
use raptorq::{ObjectTransmissionInformation, SourceBlockDecoder, SourceBlockEncoder};
use std::fmt::Write as _;
use std::fs;

struct Lcg(u32);
impl Lcg {
    fn next(&mut self) -> u32 {
        self.0 = self.0.wrapping_mul(1664525).wrapping_add(1013904223);
        self.0
    }
    fn byte(&mut self) -> u8 {
        (self.next() >> 24) as u8
    }
    fn below(&mut self, n: u32) -> u32 {
        (self.next() >> 8) % n
    }
}

fn choose(rng: &mut Lcg, mut pool: Vec<u32>, n: usize) -> Vec<u32> {
    for i in 0..n {
        let j = i + rng.below((pool.len() - i) as u32) as usize;
        pool.swap(i, j);
    }
    let mut r = pool[..n].to_vec();
    r.sort();
    r
}

fn main() {
    let dir = std::env::args().nth(1).unwrap_or("../../tests/vectors2".into());
    fs::create_dir_all(&dir).unwrap();
    let cases: Vec<(u32, u32)> = vec![(10, 16), (10, 5), (26, 16), (50, 16), (100, 16)];
    let (mut enc, mut dec) = (String::new(), String::new());
    let mut case_id = 0;
    for &(k, t) in &cases {
        let mut rng = Lcg(k * 65536 + t + 7);
        let data: Vec<u8> = (0..k * t).map(|_| rng.byte()).collect();
        let repair = k + 30;
        let config = ObjectTransmissionInformation::new((k * t) as u64, t as u16, 1, 1, 1);
        let encoder = SourceBlockEncoder::new(0, &config, &data);
        let mut packets = encoder.source_packets();
        packets.extend(encoder.repair_packets(0, repair));
        for (i, p) in packets.iter().enumerate() {
            write!(enc, "{} {} {}", k, t, i).unwrap();
            for b in p.data() {
                write!(enc, " {}", b).unwrap();
            }
            enc.push('\n');
        }
        let all_src: Vec<u32> = (0..k).collect();
        let all_rep: Vec<u32> = (k..k + repair).collect();
        let try_decode = |recv: &Vec<u32>| -> bool {
            let pk: Vec<_> = recv.iter().map(|&e| packets[e as usize].clone()).collect();
            let mut d = SourceBlockDecoder::new(0, &config, (k * t) as u64);
            match d.decode(pk) {
                Some(r) => {
                    assert_eq!(r, data, "decoder returned wrong data");
                    true
                }
                None => false,
            }
        };
        let mut lrng = Lcg(k * 65536 + t + 0x77);
        // (kind, nsrc, nrecv, draws)
        let specs: Vec<(u32, usize, usize, usize)> = vec![
            (3, 0, k as usize, 6),
            (4, (k / 4) as usize, k as usize, 4),
            (5, (k / 2) as usize, k as usize, 4),
            (7, 0, k as usize + 1, 3),
        ];
        let mut emit = |dec: &mut String, kind: u32, nsrc: usize, recv: &Vec<u32>, ok: bool| {
            write!(dec, "{} {} {} {} {} {} {}", case_id, k, t, recv.len(), ok as u32, nsrc, kind).unwrap();
            for e in recv {
                write!(dec, " {}", e).unwrap();
            }
            dec.push('\n');
            case_id += 1;
        };
        for (kind, nsrc, n, draws) in specs {
            for _ in 0..draws {
                let mut recv = choose(&mut lrng, all_src.clone(), nsrc);
                recv.extend(choose(&mut lrng, all_rep.clone(), n - nsrc));
                let ok = try_decode(&recv);
                emit(&mut dec, kind, nsrc, &recv, ok);
            }
        }
        // failure probe
        let mut found = 0;
        for _ in 0..4000 {
            if found == 3 {
                break;
            }
            let recv = choose(&mut lrng, all_rep.clone(), k as usize);
            if !try_decode(&recv) {
                emit(&mut dec, 6, 0, &recv, false);
                found += 1;
            }
        }
        eprintln!("K={} T={}: failure patterns found {}", k, t, found);
    }
    fs::write(format!("{}/encoded.txt", dir), format!("# GENERATED by tools/vectors2. Format: K T esi b0..b{{T-1}} (esi 0..K+30-1; ESI<K source, ESI>=K repair; K=(10,16),(10,5),(26,16),(50,16),(100,16))\n{}", enc)).unwrap();
    fs::write(format!("{}/decode.txt", dir), format!("# GENERATED by tools/vectors2. Format: id K T nrecv ok nsrc kind e_0..e_{{nrecv-1}} (as tests/vectors/decode.txt; kinds: 3 exactK-allrepair 4 exactK-1/4src 5 exactK-1/2src 6 reference-decoder-FAILS 7 K+1-allrepair). ok=0: decoder must fail. Source data = encoded.txt ESI<K.\n{}", dec)).unwrap();
    eprintln!("decode cases: {}", case_id);
}
