#!/usr/bin/env python3
"""Generate tools/profile/mb_leaf_<M>.bend : Vec with M-word leaves (xor / muladd chains, 1 thread).
usage: gen_mb_leaf.py M ; then bend tools/profile/mb_leaf_M.bend -o build/mb_leaf_M ; ./build/mb_leaf_M -- <words> <ops> <mode>"""
import sys
M=int(sys.argv[1])
KER=int(sys.argv[2]) if len(sys.argv)>2 else 0  # 0 G.mulw, 1 unrolled swar, 2 bit-sliced hoisted k_i, 3 log/exp
ws=[f"w{i}" for i in range(M)]
fields=", ".join(f"{w}: U32" for w in ws)
a=", ".join(f"a{i}" for i in range(M)); b=", ".join(f"b{i}" for i in range(M))
xo=", ".join(f"U32.xor(a{i}, b{i})" for i in range(M))
KP={0:"+c: U32, ",1:"+c: U32, ",2:"".join(f"+k{i}: U32, " for i in range(8)),3:"+c: U32, "}[KER]
KA={0:"c, ",1:"c, ",2:"".join(f"k{i}, " for i in range(8)),3:"c, "}[KER]
def kern(i):
    if KER==0: return f"G.mulw(c, b{i})"
    if KER==1: return f"mulw1(c, b{i})"
    if KER==2: return f"mulw2(k0, k1, k2, k3, k4, k5, k6, k7, b{i})"
    return f"mulw3(c, b{i})"
ma=", ".join(f"U32.xor(a{i}, {kern(i)})" for i in range(M))
kdefs=open("tools/profile/mb_mulw.bend").read()
import re
def grab(name):
    m=re.search(r"def "+name+r"\(.*?(?=\n\ndef |\n# |\Z)",kdefs,re.S)
    return m.group(0)
KD="def xt(+w: U32) -> U32:\n  G.xtime4(w)\n\n"+grab("mulw1")+"\n\n"+grab("mulw2")+"\n\n"+grab("mulw3")+"\n\n"
sm=" + ".join(f"w{i}" for i in range(M))
bl=", ".join(f"(x + {i} : U32)" for i in range(M))
KCALL=("          chain(p, mode, (c + 1 : U32), vma(cc, acc, src), src)" if KER!=2 else
"          +k1 = G.xtime(cc)\n          +k2 = G.xtime(k1)\n          +k3 = G.xtime(k2)\n          +k4 = G.xtime(k3)\n          +k5 = G.xtime(k4)\n          +k6 = G.xtime(k5)\n          +k7 = G.xtime(k6)\n          chain(p, mode, (c + 1 : U32), vma(cc, k1, k2, k3, k4, k5, k6, k7, acc, src), src)")
src=f'''# generated by gen_mb_leaf.py {M}: tree whose leaves hold {M} words
import Base
import ../../src/gf256.bend as G

type V is Data:
  N{{l: V, r: V}}
  L{{{fields}}}

def bld(+d: Nat, +x: U32) -> V:
  match d:
    case 0n:
      L{{{bl}}}
    case 1n+p:
      N{{bld(p, (x * 1664525 + 1013904223 : U32)), bld(p, (x * 22695477 + 1 : U32))}}

def vxor(a: V, b: V) -> V:
  match a b:
    case N{{al, ar}} N{{bl, br}}:
      N{{vxor(al, bl), vxor(ar, br)}}
    case L{{{a}}} L{{{b}}}:
      L{{{xo}}}
    case x _:
      x

{KD}def vma({KP}a: V, b: V) -> V:
  match a b:
    case N{{al, ar}} N{{bl, br}}:
      N{{vma({KA}al, bl), vma({KA}ar, br)}}
    case L{{{a}}} L{{{b}}}:
      L{{{ma}}}
    case x _:
      x

def sum(v: V) -> U32:
  match v:
    case N{{l, r}}:
      (sum(l) + sum(r) : U32)
    case L{{{", ".join(ws)}}}:
      ({sm} : U32)

def chain(n: Nat, +mode: U32, +c: U32, acc: V, +src: V) -> V:
  match n:
    case 0n:
      acc
    case 1n+p:
      match mode:
        case 0:
          chain(p, mode, c, vxor(acc, src), src)
        case _:
          +cc = ((c .&. 255 : U32) .|. 2 : U32)
{KCALL}

def run(+w: U32, +m: U32, +mode: U32) -> IO(Unit):
  +d = U32.log2((w / {M} : U32))
  +a = bld(d, 7)
  +b = bld(d, 99)
  do IO<Unit>:
    IO.print("warm " ++ U32.show((sum(a) + sum(b) : U32)))
    t0 : Nat <- IO.now()
    IO.print("sum=" ++ U32.show(sum(chain(U32.to_nat(m), mode, 3, a, b))))
    t1 : Nat <- IO.now()
    IO.print("RESULT leaf={M} words=" ++ U32.show(w) ++ " ops=" ++ U32.show(m) ++ " mode=" ++ U32.show(mode) ++ " ms=" ++ Nat.show((t1 - t0 : Nat)))

def rd(s: String, d: U32) -> U32:
  Maybe.default(&2, U32, U32.read(s), d)

def run_args(args: List<String>) -> IO(Unit):
  match args:
    case p <> a <> b <> c <> rest:
      run(rd(a, 64), rd(b, 1000), rd(c, 1))
    case _:
      run(64, 1000, 1)

def main() -> IO(Unit):
  do IO<Unit>:
    args : List<String> <- IO.args()
    run_args(args)
'''
open(f"tools/profile/mb_leaf_{M}_{KER}.bend","w").write(src)
