#!/usr/bin/env python3
"""Generate tests/constraints_test.bend from tests/vectors/{constraints,intermediate,encoded}.txt.

Run from the repo root:  python3 tools/gen_constraints_test.py   (MAX_K=100 env var limits the cases)
Then:                    bend tests/constraints_test.bend
(Tuple itself is covered by tests/tables_test.bend; tuples.txt is not needed here because the
constraint rows of constraints.txt are built from Tuple and compared term by term.)
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V = os.path.join(ROOT, "tests", "vectors")
MAX_K = int(os.environ.get("MAX_K", "1000"))

def rows(name):
    for line in open(os.path.join(V, name)):
        line = line.strip()
        if line and not line.startswith("#"):
            yield list(map(int, line.split()))

def pack(bs):
    bs = list(bs) + [0] * ((-len(bs)) % 4)
    return [(bs[i] << 24) | (bs[i+1] << 16) | (bs[i+2] << 8) | bs[i+3] for i in range(0, len(bs), 4)]

def vec(bs):
    return "G.Vec.from_list([" + ",".join(map(str, pack(bs))) + "])"

cons = {}
for r in rows("constraints.txt"):
    cons.setdefault(r[0], []).extend(r[2:])      # kind, n, col, val, ...
enc, inter = {}, {}
for r in rows("encoded.txt"):
    enc.setdefault((r[0], r[1]), []).append(r[3:])
for r in rows("intermediate.txt"):
    inter.setdefault((r[0], r[1]), []).append(r[3:])
cases = sorted(c for c in enc if c[0] <= MAX_K)

HEAD = r'''# GENERATED by tools/gen_constraints_test.py from tests/vectors -- DO NOT EDIT.
# Run (from the repo root):  bend tests/constraints_test.bend
# Prints one line per group; exits non-zero (IO.die) on any failure.
#  (1) fixed() ++ source_rows() equal the independently derived matrix rows of
#      tests/vectors/constraints.txt (K'=10, 26): same term sets and coefficients
#  (2) encode() on the golden intermediate symbols gives the golden encoded symbols
#  (3) every row of fixed()+source_rows() and of received_rows() evaluates to its rhs on the
#      golden intermediate symbols (A*C = D, zero rhs for the S+H rows and padding rows)
import Base
import ../src/gf256.bend as G
import ../src/tables.bend as T
import ../src/rfc_funcs.bend as R
import ../src/types.bend as Y
import ../src/constraints.bend as C

def ck.go(eq: Bool) -> U32:
  match eq:
    case True{}:
      0
    case False{}:
      1

def ck(+a: U32, +b: U32) -> U32:
  ck.go(U32.is_eq(a, b))

def sp_of.go(m: Maybe<&2, T.SP>) -> T.SP:
  match m:
    case Some{sp}:
      sp
    case None{}:
      T.SP{0, 0, 0, 0, 0, 0}

# Table 2 row for the smallest K' >= k
def sp_of(+k: U32) -> T.SP:
  sp_of.go(R.params(k))

# ---- list utilities -------------------------------------------------------

def lists_eq(xs: List<&2, U32>, ys: List<&2, U32>) -> U32:
  match xs ys:
    case Nil{} Nil{}:
      0
    case Con{x, xt} Con{y, yt}:
      (ck(x, y) + lists_eq(xt, yt) : U32)
    case _ _:
      1

def vec_eq(a: G.Vec, b: G.Vec) -> U32:
  lists_eq(G.Vec.to_list(a, []), G.Vec.to_list(b, []))

def len_terms(xs: List<&2, Y.Term>) -> U32:
  match xs:
    case Nil{}:
      0
    case Con{x, t}:
      (1 + len_terms(t) : U32)

def b2u(b: Bool) -> U32:
  match b:
    case True{}:
      1
    case False{}:
      0

# ---- (1) matrix rows ------------------------------------------------------

type Res is Data:
  Res{f: U32, rest: List<&2, U32>}

# number of terms equal to (col, val)
def cnt(mine: List<&2, Y.Term>, +col: U32, +val: U32) -> U32:
  match mine:
    case Nil{}:
      0
    case Con{t, rest}:
      match t:
        case Y.Term{c, v}:
          ((b2u(U32.is_eq(c, col)) * b2u(U32.is_eq(v, val)) : U32) + cnt(rest, col, val) : U32)

def res_add(+x: U32, r: Res) -> Res:
  match r:
    case Res{f, rest}:
      Res{(x + f : U32), rest}

# consume n (col, val) pairs of flat; each must occur exactly once among mine
def chk.terms(n: Nat, flat: List<&2, U32>, +mine: List<&2, Y.Term>) -> Res:
  match n:
    case 0n:
      Res{0, flat}
    case 1n+p:
      match flat:
        case Con{c, t1}:
          match t1:
            case Con{v, t2}:
              res_add(ck(cnt(mine, c, v), 1), chk.terms(p, t2, mine))
            case Nil{}:
              Res{1, []}
        case Nil{}:
          Res{1, []}

def chk.row(+n: U32, flat: List<&2, U32>, +cols: List<&2, Y.Term>) -> Res:
  res_add(ck(len_terms(cols), n), chk.terms(U32.to_nat(n), flat, cols))

# flat row record: kind n (col val)*n
def chk.row2(r: Y.Row, flat: List<&2, U32>) -> Res:
  match flat:
    case Con{kind, f1}:
      match f1:
        case Con{n, f2}:
          chk.row(n, f2, Y.Row.cols(r))
        case Nil{}:
          Res{1, []}
    case Nil{}:
      Res{1, []}

def chk.step(r: Y.Row, st: Res) -> Res:
  match st:
    case Res{f, fl}:
      res_add(f, chk.row2(r, fl))

# all rows consumed: the flat list must be exhausted too
def chk.end(st: Res) -> U32:
  match st:
    case Res{f, fl}:
      match fl:
        case Nil{}:
          f
        case Con{h, t}:
          (f + 1 : U32)

def chk.rows(rs: List<&2, Y.Row>, st: Res) -> U32:
  match rs:
    case Nil{}:
      chk.end(st)
    case Con{r, rest}:
      chk.rows(rest, chk.step(r, st))

def zeros(+n: Nat, +z: G.Vec) -> List<&2, G.Vec>:
  List.replicate(G.Vec, n, z)

# fixed() ++ source_rows(K' zero symbols) against the golden flat matrix
def t_matrix(+kp: U32, flat: List<&2, U32>) -> U32:
  +sp = sp_of(kp)
  +z = C.zero(16)
  chk.rows(List.append(&2, Y.Row, C.fixed(sp, 16), C.source_rows(sp, zeros(U32.to_nat(kp), z))), Res{0, flat})

# ---- (2)/(3) golden symbols ----------------------------------------------

# sum of coef*C[col] over cols, then compare with rhs
def eval.go(+tr: C.ITree, ts: List<&2, Y.Term>, acc: G.Vec) -> G.Vec:
  match ts:
    case Nil{}:
      acc
    case Con{t, rest}:
      match t:
        case Y.Term{col, coef}:
          eval.go(tr, rest, G.Vec.muladd(coef, acc, C.ix.get(tr, col, G.VNil{})))

def row_ok(+tr: C.ITree, r: Y.Row) -> U32:
  match r:
    case Y.Row{cols, +rhs}:
      vec_eq(eval.go(tr, cols, G.Vec.zeros(rhs)), rhs)

def rows_ok(+tr: C.ITree, rs: List<&2, Y.Row>) -> U32:
  match rs:
    case Nil{}:
      0
    case Con{r, rest}:
      (row_ok(tr, r) + rows_ok(tr, rest) : U32)

def enc_ok(es: List<&2, G.Vec>, +sp: T.SP, +tr: C.ITree, +k: U32, +kp: U32, +esi: U32) -> U32:
  match es:
    case Nil{}:
      0
    case Con{e, rest}:
      (vec_eq(C.encode_idx(sp, tr, C.isi_of(esi, k, kp)), e) + enc_ok(rest, sp, tr, k, kp, (esi + 1 : U32)) : U32)

def take_syms(+n: Nat, xs: List<&2, G.Vec>) -> List<&2, G.Vec>:
  List.take(&2, G.Vec, xs, n)

def rcvs(es: List<&2, G.Vec>, +esi: U32) -> List<&2, Y.Rcv>:
  match es:
    case Nil{}:
      []
    case Con{e, rest}:
      Y.Rcv{esi, e} <> rcvs(rest, (esi + 1 : U32))

# the three checks for one (K, T) case: encode / A*C=D / received rows
def run_case(+k: U32, +t: U32, +inter: List<&2, G.Vec>, +es: List<&2, G.Vec>) -> U32:
  +sp = sp_of(k)
  +kp = R.Kp(sp)
  +tr = C.index(inter)
  a = enc_ok(es, sp, tr, k, kp, 0)
  b = rows_ok(tr, List.append(&2, Y.Row, C.fixed(sp, t), C.source_rows(sp, take_syms(U32.to_nat(k), es))))
  c = rows_ok(tr, C.received_rows(sp, k, rcvs(es, 0)))
  d = vec_eq(C.encode(sp, inter, kp), C.encode_idx(sp, tr, kp))
  (a + b + c + d : U32)

def line.go(name: String, +f: U32, ok: Bool) -> String:
  match ok:
    case True{}:
      "PASS " ++ name
    case False{}:
      "FAIL " ++ name ++ " (" ++ U32.show(f) ++ " mismatches)"

def line(name: String, +f: U32) -> String:
  line.go(name, f, U32.is_zero(f))

def done.go(+f: U32, ok: Bool) -> IO(Unit):
  match ok:
    case True{}:
      IO.print("ALL TESTS PASSED")
    case False{}:
      IO.die(Unit, 1, "FAILED: " ++ U32.show(f) ++ " mismatches in total")

def done(+f: U32) -> IO(Unit):
  done.go(f, U32.is_zero(f))

'''
body = []
for kp, flat in sorted(cons.items()):
    body.append("def mat_%d() -> List<&2, U32>:\n  [%s]\n" % (kp, ",".join(map(str, flat))))
for (k, t) in cases:
    body.append("def inter_%d_%d() -> List<&2, G.Vec>:\n  [%s]\n" % (k, t, ",\n   ".join(vec(b) for b in inter[(k, t)])))
    body.append("def enc_%d_%d() -> List<&2, G.Vec>:\n  [%s]\n" % (k, t, ",\n   ".join(vec(b) for b in enc[(k, t)])))
    body.append("def case_%d_%d() -> U32:\n  run_case(%d, %d, inter_%d_%d(), enc_%d_%d())\n" % (k, t, k, t, k, t, k, t))

main = ["def main() -> IO(Unit):", "  do IO<Unit>:"]
names = []
for kp in sorted(cons):
    main.append("    +m%d : U32 = t_matrix(%d, mat_%d())" % (kp, kp, kp))
    main.append("    IO.print(line(\"matrix rows K'=%d (fixed + LT rows == constraints.txt)\", m%d))" % (kp, kp))
    names.append("m%d" % kp)
for (k, t) in cases:
    n = "c%d_%d" % (k, t)
    main.append("    +%s : U32 = case_%d_%d()" % (n, k, t))
    main.append("    IO.print(line(\"K=%d T=%d: encode, A*C=D, received rows\", %s))" % (k, t, n))
    names.append(n)
main.append("    done((%s : U32))" % " + ".join(names))
open(os.path.join(ROOT, "tests", "constraints_test.bend"), "w").write(HEAD + "\n".join(body) + "\n" + "\n".join(main) + "\n")
print("cases:", cases)
