#!/usr/bin/env python3
"""Generate tests/codec_fixtures.bend for tests/codec_test.bend from tests/vectors*/ (golden RFC vectors).

Two vector sets: tests/vectors (tools/vectors) and tests/vectors2 (tools/vectors2, harder decode cases).
Per set S (suffix "" and "2") the fixture defs are
  enc<S>() : [ncases] then per case [K, T, R, (K+R)*ceil(T/4) words]   encoded symbols for ESI 0..K+R-1
             (words = 4 octets big-endian packed, T not a multiple of 4 zero padded; the K source symbols are
             the first K, asserted equal to source.txt where present)
  dec<S>() : [ndec] then per decode case [case_index, ok, nrecv, e_0 .. e_{nrecv-1}]
             (case_index = index into enc<S>; the received data are the encoded symbols of those ESIs)
Usage: python3 tools/gen_codec_test.py        (MAX_K=100 limits the cases)
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
MAX_K = int(os.environ.get("MAX_K", "100000"))

def rows(path):
    for line in open(path):
        line = line.split("#")[0] if line.lstrip().startswith("#") else line.split("   #")[0]
        if not line.strip():
            continue
        yield list(map(int, line.split()))

def words(sym):
    sym = list(sym) + [0] * (-len(sym) % 4)
    return [(sym[i] << 24) | (sym[i+1] << 16) | (sym[i+2] << 8) | sym[i+3] for i in range(0, len(sym), 4)]

def emit_chunked(f, name, flat, chunk=600):
    """A single huge list literal overflows the checker's stack: emit chunk-sized defs and append them."""
    chunks = [flat[i:i + chunk] for i in range(0, len(flat), chunk)] or [[]]
    for k, ch in enumerate(chunks):
        f.write("def %s_c%d() -> List<&2, U32>:\n  [%s]\n\n" % (name, k, ", ".join(str(v) for v in ch)))
    expr = "%s_c%d()" % (name, len(chunks) - 1)
    for k in range(len(chunks) - 2, -1, -1):
        expr = "List.append(&2, U32, %s_c%d(), %s)" % (name, k, expr)
    f.write("def %s() -> List<&2, U32>:\n  %s\n\n" % (name, expr))

def load(d):
    vec = os.path.join(ROOT, "tests", d)
    enc = {}
    for r in rows(os.path.join(vec, "encoded.txt")):
        enc.setdefault((r[0], r[1]), []).append(r[3:])
    src = {}
    if os.path.exists(os.path.join(vec, "source.txt")):
        for r in rows(os.path.join(vec, "source.txt")):
            src.setdefault((r[0], r[1]), []).append(r[3:])
    keys = [kt for kt in enc if kt[0] <= MAX_K]
    flat_enc = [len(keys)]
    for (k, t) in keys:
        syms = enc[(k, t)]
        if (k, t) in src:
            assert syms[:k] == src[(k, t)], (k, t)
        for i, s in enumerate(syms):
            assert len(s) == t
        flat_enc += [k, t, len(syms) - k]
        for s in syms:
            flat_enc += words(s)
    idx = {kt: i for i, kt in enumerate(keys)}
    decs = []
    for r in rows(os.path.join(vec, "decode.txt")):
        _id, k, t, n, ok, nsrc, kind = r[:7]
        es = r[7:]
        assert len(es) == n
        if (k, t) in idx:
            decs.append([idx[(k, t)], ok, n] + es)
    flat_dec = [len(decs)]
    for d_ in decs:
        flat_dec += d_
    return flat_enc, flat_dec, len(keys), len(decs)

def main():
    path = os.path.join(ROOT, "tests", "codec_fixtures.bend")
    with open(path, "w") as f:
        f.write("# GENERATED by tools/gen_codec_test.py from tests/vectors and tests/vectors2 -- DO NOT EDIT.\n")
        f.write("# enc*: [ncases] then per case [K, T, R, (K+R)*ceil(T/4) packed words]; dec*: [n] then per case [case, ok, nrecv, esis...]\n")
        for suffix, d in (("", "vectors"), ("2", "vectors2")):
            fe, fd, ne, nd = load(d)
            emit_chunked(f, "enc" + suffix, fe)
            emit_chunked(f, "dec" + suffix, fd)
            print("%s: %d (K,T) cases, %d decode cases, %d + %d numbers" % (d, ne, nd, len(fe), len(fd)), file=sys.stderr)
    print("wrote", path, os.path.getsize(path), "bytes", file=sys.stderr)

main()
