#!/usr/bin/env python3
"""Generate tests/blocks_fixtures.bend for tests/blocks_test.bend from tests/vectors3/ (multi-block golden vectors, tools/vectors3).

Every fixture def is a flat list of U32 (chunked: a single huge list literal overflows the checker's stack):
  oti()  : [n] then per object [id, seed, F, T, Z, N, Al, Kt, KL, KS, ZL, ZS, 12 serialized OTI octets]
  pk()   : per object, in oti() order: [npk] then per packet [sbn, esi, ceil(T/4) packed words (4 octets big-endian, zero padded)]
  dec()  : [n] then per scenario [object index, kind, nrecv, sbn_0, esi_0, ...]
  part() : [n] then [I, J, IL, IS, JL, JS]*          kmax(): [n] then [x, kmax]*
  par()  : [n] then [F, P', Al, SS, WS, T, Z, N, Al]*
Usage: python3 tools/gen_blocks_test.py
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
V = os.path.join(ROOT, "tests", "vectors3")

def rows(name):
    for line in open(os.path.join(V, name)):
        if line.startswith("#") or not line.strip():
            continue
        yield list(map(int, line.split()))

def words(sym):
    sym = list(sym) + [0] * (-len(sym) % 4)
    return [(sym[i] << 24) | (sym[i+1] << 16) | (sym[i+2] << 8) | sym[i+3] for i in range(0, len(sym), 4)]

def emit_chunked(f, name, flat, chunk=600):
    chunks = [flat[i:i + chunk] for i in range(0, len(flat), chunk)] or [[]]
    for k, ch in enumerate(chunks):
        f.write("def %s_c%d() -> List<&2, U32>:\n  [%s]\n\n" % (name, k, ", ".join(str(v) for v in ch)))
    expr = "%s_c%d()" % (name, len(chunks) - 1)
    for k in range(len(chunks) - 2, -1, -1):
        expr = "List.append(&2, U32, %s_c%d(), %s)" % (name, k, expr)
    f.write("def %s() -> List<&2, U32>:\n  %s\n\n" % (name, expr))

def main():
    objs = list(rows("oti.txt"))
    flat_oti = [len(objs)]
    for o in objs:
        assert len(o) == 12 + 12
        flat_oti += o
    tsize = {o[0]: o[3] for o in objs}
    pk = {}
    for r in rows("packets.txt"):
        pk.setdefault(r[0], []).append(r)
    flat_pk = []
    for o in objs:
        ps = pk[o[0]]
        flat_pk.append(len(ps))
        for r in ps:
            assert len(r) == 3 + tsize[o[0]]
            flat_pk += [r[1], r[2]] + words(r[3:])
    index = {o[0]: i for i, o in enumerate(objs)}
    decs = list(rows("decode.txt"))
    flat_dec = [len(decs)]
    for r in decs:
        assert len(r) == 3 + 2 * r[2]
        flat_dec += [index[r[0]], r[1], r[2]] + r[3:]
    part = list(rows("partition.txt"))
    kmax = list(rows("kmax.txt"))
    par = list(rows("params.txt"))
    path = os.path.join(ROOT, "tests", "blocks_fixtures.bend")
    with open(path, "w") as f:
        f.write("# GENERATED by tools/gen_blocks_test.py from tests/vectors3 -- DO NOT EDIT.\n")
        f.write("# oti/pk/dec/part/kmax/par: flat U32 lists, layouts in the generator's docstring\n")
        emit_chunked(f, "oti", flat_oti)
        emit_chunked(f, "pk", flat_pk)
        emit_chunked(f, "dec", flat_dec)
        emit_chunked(f, "part", [len(part)] + [x for r in part for x in r])
        emit_chunked(f, "kmax", [len(kmax)] + [x for r in kmax for x in r])
        emit_chunked(f, "par", [len(par)] + [x for r in par for x in r])
    print("%d objects, %d packets, %d decode scenarios, %d partition, %d kmax, %d params cases -> %s (%d bytes)" % (
        len(objs), sum(len(v) for v in pk.values()), len(decs), len(part), len(kmax), len(par), path, os.path.getsize(path)), file=sys.stderr)

main()
